#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =  -Iinclude -I$(BOOST_HOME)/include
CFLAGS =  -std=c++0x -Wall
RESINC = 
LIBDIR =  -L$(BOOST_HOME)/lib
#LIB =  $(BOOST_HOME)/lib/libboost_date_time.a
LIB = -lboost_date_time
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -std=c++0x -g -w
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/watdiv

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O3 -std=c++0x -w
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/watdiv

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/dictionary.o $(OBJDIR_DEBUG)/src/model.o $(OBJDIR_DEBUG)/src/statistics.o $(OBJDIR_DEBUG)/src/volatility_gen.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/dictionary.o $(OBJDIR_RELEASE)/src/model.o $(OBJDIR_RELEASE)/src/statistics.o $(OBJDIR_RELEASE)/src/volatility_gen.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)/src/dictionary.o: src/dictionary.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/dictionary.cpp -o $(OBJDIR_DEBUG)/src/dictionary.o

$(OBJDIR_DEBUG)/src/model.o: src/model.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/model.cpp -o $(OBJDIR_DEBUG)/src/model.o

$(OBJDIR_DEBUG)/src/statistics.o: src/statistics.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/statistics.cpp -o $(OBJDIR_DEBUG)/src/statistics.o

$(OBJDIR_DEBUG)/src/volatility_gen.o: src/volatility_gen.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/volatility_gen.cpp -o $(OBJDIR_DEBUG)/src/volatility_gen.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)/src/dictionary.o: src/dictionary.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/dictionary.cpp -o $(OBJDIR_RELEASE)/src/dictionary.o

$(OBJDIR_RELEASE)/src/model.o: src/model.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/model.cpp -o $(OBJDIR_RELEASE)/src/model.o

$(OBJDIR_RELEASE)/src/statistics.o: src/statistics.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/statistics.cpp -o $(OBJDIR_RELEASE)/src/statistics.o

$(OBJDIR_RELEASE)/src/volatility_gen.o: src/volatility_gen.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/volatility_gen.cpp -o $(OBJDIR_RELEASE)/src/volatility_gen.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

